---

- hosts: all
  remote_user: root
  become: yes
  roles:
    - role: angstwad.docker_ubuntu
      docker_opts: "--bip 192.168.100.1/24 --dns 8.8.8.8"
  tasks:
    - name: Install the package "vim"
      apt:
        name: vim
        state: present
