---

- name: install requirement of neovim
  apt: name={{ item }} state=present
  with_items:
    - software-properties-common
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip

- name: add apt repository for neovim
  apt_repository:
    repo: "ppa:neovim-ppa/unstable"

- name: install neovim
  apt: name=neovim state=present

- name: set neovim to alternative command of vim
  alternatives:
    name: vim
    path: /usr/bin/nvim
    priority: 60

